server:
  port: 9700
spring:
  application:
    name: nice-auth
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.12.178:6380
        group: nice
  redis:
    database: 0
    host: 159.75.12.178
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: "*"