spring:
  application:
    name: gateway1
  datasource:
    username: babymo
    password: Qwer13579
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1n1jv17973394m50o.mysql.rds.aliyuncs.com:3306
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.12.178:6380
        group: nice
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Nice-Auth
          uri: lb://nice-auth
          predicates:
            - Path=/auth/**
        - id: test
          uri: lb://consumer1
          predicates:
            - Path=/test/**
      default-filters:
          - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9700/rsa/publicKey"
  redis:
    database: 0
    host: 159.75.12.178
    port: 6379

secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/auth/oauth/token"
server:
  port: 9800

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl